Homework to Lec. 9
AlesiaRebkavets/Hometask_Lec9 pull request #1
Opened 2022-11-27 21:12 UTC by AlesiaRebkavets

2022-11-30 08:02 UTC, ezhukovskaya requested changes

2022-11-30 08:02 UTC, ezhukovskaya commented on Hometask_Lec9/Program.cs
> +    internal class Program
и зачем нам этот класс?

2022-11-30 08:02 UTC, ezhukovskaya commented on Hometask_Lec9/Task1.cs
> +        //static void Main()
у тебя в каждом класс зачем-то существует метод Main, у тебя пустует при этом класс Program, почему бы там не создать один единственный Main и запускать всё там?

2022-11-30 08:02 UTC, ezhukovskaya commented on Hometask_Lec9/Task1.cs
> +            for (int i = 0; i < numbers.Count; i++)
попробуй заменить такую сложную конструкцию на linq, весь метод сократится до одной строки

2022-11-30 08:02 UTC, ezhukovskaya commented on Hometask_Lec9/Task1.cs
> +            Console.WriteLine("Vvedite dlinu spiska");                              // ask user to enter a list length
давай в следующих домашках писать уже на англе, а то транслит не комильфо)

2022-11-30 08:02 UTC, ezhukovskaya commented on Hometask_Lec9/Task1.cs
> +                        i--;                                                                  // decrement i by one to enter the number again
а хорошо ли это? мы так бесконечно можем вводить ерунду, получается бесконечный цикл, давай лучше будем пробрасывать исключение и выход из цикла соответсвенно

2022-11-30 08:02 UTC, ezhukovskaya commented on Hometask_Lec9/Task1.cs
> +                EnterListElement(numbers);                                          // and recursion is used
тут тоже получается бесконечная рекурсия

2022-11-30 08:02 UTC, ezhukovskaya commented on Hometask_Lec9/Task1.cs
> +                        i--;                                                                  // decrement i by one to enter the number again
после этого можно будет красиво переписать на linq

2022-11-30 08:02 UTC, ezhukovskaya commented on Hometask_Lec9/Task1.cs
> +        private static List<int> EnterListElement(List<int> numbers)
зачем нам пустой список в качестве параметра

2022-11-30 08:02 UTC, ezhukovskaya commented on Hometask_Lec9/Task1.cs
> +        public static string OutputOfListElements(List<int> numbers)
перепиши весь метод через linq

2022-11-30 08:02 UTC, ezhukovskaya commented on Hometask_Lec9/Task1.cs
> +        public static string FiveLettersWordOutput(List<string> words)          // method returns string containing words from a list, containing 5 symbols
перепиши весь метод через linq

2022-11-30 08:02 UTC, ezhukovskaya commented on Hometask_Lec9/Task1.cs
> +                FindWordsOfACertainLength(words);                                  // and recursion is used
бесконечная рекурсия

2022-11-30 08:02 UTC, ezhukovskaya commented on Hometask_Lec9/Task1.cs
> +                bool ifPresent = words.Any(s => s.Length == n);                         // determing if words of the entered lenght exist in collection
лишние действия, можно сразу вытащит все соответсвия длине через Select без использования if, если совпадений не будет, то просто вернётся пустой список. Если словпадения есть, то выводишь слова, если нет, то if(!yourList.Any()){таких слов нет}

2022-11-30 08:02 UTC, ezhukovskaya commented on Hometask_Lec9/Task1.cs
> +                FindWordsOfACertainLength(words);                                  // and recursion is used
поправь везде

2022-11-30 08:02 UTC, ezhukovskaya commented on Hometask_Lec9/Task3.cs
> +        public static void AddElementsToQueue(Queue<int> numbers)
пустая очередь тут не нужна

2022-11-30 08:02 UTC, ezhukovskaya commented on Hometask_Lec9/Task3.cs
> +            for (int i = 0; i < 3; i++)               // deleting the last one added element from stack and adding it's value to a string variable 's' in cycle
почему 3?

2022-11-30 08:02 UTC, ezhukovskaya commented on Hometask_Lec9/Task4.cs
> +            City Katowice = new(321000, 164.67);           // initialization of objects of City type
можно просто заменить на var

2022-11-30 08:02 UTC, ezhukovskaya commented on Hometask_Lec9/Task4.cs
> +            City Katowice = new(321000, 164.67);           // initialization of objects of City type
поправь везде

2022-11-30 08:02 UTC, ezhukovskaya commented on Hometask_Lec9/Task4.cs
> +            names.Reverse();     // reverse the list elements
names сразу можно было в обратном порядке, OrderByDescending

2022-11-30 08:02 UTC, ezhukovskaya commented on Hometask_Lec9/Task4.cs
> +            foreach (var d in dictionary)        // for all key-values in dictionary
linq

2022-11-30 08:02 UTC, ezhukovskaya commented on Hometask_Lec9/Task4.cs
> +            foreach (var d in dictionary)                 // for all key-values in dictionary
linq

2022-12-11 01:10 UTC, AlesiaRebkavets commented on Hometask_Lec9/Task4.cs
> +            foreach (var d in dictionary)                 // for all key-values in dictionary
done

2022-12-11 01:15 UTC, AlesiaRebkavets commented on Hometask_Lec9/Task4.cs
> +            foreach (var d in dictionary)        // for all key-values in dictionary
done

2022-12-11 15:02 UTC, AlesiaRebkavets commented on Hometask_Lec9/Task4.cs
> +            names.Reverse();     // reverse the list elements
done

2022-12-11 15:03 UTC, AlesiaRebkavets commented on Hometask_Lec9/Task4.cs
> +            City Katowice = new(321000, 164.67);           // initialization of objects of City type
а как тут заменить на var? в задании написано: "Создайте класс City, где есть поля int население, double площадь. Создайте словарь, где Key – название города, а Value – сооттветствующий названию города объект типа City."

2022-12-11 15:03 UTC, AlesiaRebkavets commented on Hometask_Lec9/Task3.cs
> +            for (int i = 0; i < 3; i++)               // deleting the last one added element from stack and adding it's value to a string variable 's' in cycle
там должно быть три буквы
"Напишите программу, которая принимает на вход три буквы и отображает их в обратном порядке. Используйте Stack."

2022-12-11 15:04 UTC, AlesiaRebkavets commented on Hometask_Lec9/Task3.cs
> +        public static void AddElementsToQueue(Queue<int> numbers)
corrected

2022-12-11 15:04 UTC, AlesiaRebkavets commented on Hometask_Lec9/Task1.cs
> +                bool ifPresent = words.Any(s => s.Length == n);                         // determing if words of the entered lenght exist in collection
done

2022-12-11 15:52 UTC, AlesiaRebkavets commented on Hometask_Lec9/Task1.cs
> +        public static string FiveLettersWordOutput(List<string> words)          // method returns string containing words from a list, containing 5 symbols
done

2022-12-11 16:00 UTC, AlesiaRebkavets commented on Hometask_Lec9/Task1.cs
> +        public static string OutputOfListElements(List<int> numbers)
done

2022-12-11 16:07 UTC, AlesiaRebkavets commented on Hometask_Lec9/Task1.cs
> +        private static List<int> EnterListElement(List<int> numbers)
corrected

2022-12-11 16:07 UTC, AlesiaRebkavets commented on Hometask_Lec9/Task1.cs
> +            Console.WriteLine("Vvedite dlinu spiska");                              // ask user to enter a list length
окей)

2022-12-11 18:14 UTC, AlesiaRebkavets commented on Hometask_Lec9/Task1.cs
> +            for (int i = 0; i < numbers.Count; i++)
done

2022-12-12 09:50 UTC, AlesiaRebkavets commented on Hometask_Lec9/Program.cs
> +    internal class Program
исправила
добавила в него main метод

2022-12-12 09:51 UTC, AlesiaRebkavets commented on Hometask_Lec9/Task1.cs
> +        //static void Main()
done

2022-12-12 09:51 UTC, AlesiaRebkavets commented on Hometask_Lec9/Task1.cs
> +                        i--;                                                                  // decrement i by one to enter the number again
done

2022-12-12 09:51 UTC, AlesiaRebkavets commented on Hometask_Lec9/Task1.cs
> +                EnterListElement(numbers);                                          // and recursion is used
done

2022-12-12 09:51 UTC, AlesiaRebkavets commented on Hometask_Lec9/Task1.cs
> +                FindWordsOfACertainLength(words);                                  // and recursion is used
corrected

2022-12-14 15:06 UTC, ezhukovskaya approved these changes

2022-12-15 11:05 UTC, merged